Fix duplicate `groups` in kwargs of Conv2d
facebookresearch/CrypTen pull request #227
Opened 2021-03-09 16:37 UTC by jeffreysijuntan

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs change / refactoring / dependency upgrade

## Motivation and Context / Related issue

This pull request addresses the following two issues:
1. In current `__patched_conv2d_ops` in `CUDALongTensor`, we assume the default `group` is 1. If the user pass in `group` as kwargs, then we will encounter duplicate kwargs error. This diff addresses this issue by explicitly checking whether `group` is passed in as kwargs.
2. Specify the `device` of kernel for average pooling in `gradients.py`. If `device` is not specified, then running `Avgpool2d` layer on GPU will throw a `device doesn't match` error.

## How Has This Been Tested (if it applies)
Tested training of LeNet on GPU. 

## Checklist

- [ ] The documentation is up-to-date with the changes I made.
- [ ] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [ ] All tests passed, and additional code has been covered with new tests.

2021-03-16 19:01 UTC, knottb approved these changes

2021-03-17 15:03 UTC, knottb commented
Appears that CircleCI is showing failures in benchmarks due to the MNIST server being down.

This is not a problem with the code here but is blocking our ability to merge this PR for now. The status of the MNIST server can be tracked [here](https://github.com/pytorch/vision/issues/3554).

I'm rerunning the CircleCI test to see if we can get this landed.

2021-03-17 18:55 UTC, jeffreysijuntan commented
> Appears that CircleCI is showing failures in benchmarks due to the MNIST server being down.
> 
> This is not a problem with the code here but is blocking our ability to merge this PR for now. The status of the MNIST server can be tracked [here](https://github.com/pytorch/vision/issues/3554).
> 
> I'm rerunning the CircleCI test to see if we can get this landed.

No problem. Thanks!

2021-03-22 16:47 UTC, knottb commented
Looks like `conv_transpose2d` is failing now. Going to look into this a bit more to gather information.

```
~ Test test.test_arithmetic.TestArithmetic.test_conv2d_rectangular_image_many_channels failed ~
===========
Exceptions:
===========
** Process 0 ** :
Traceback (most recent call last):
  File "/home/circleci/CrypTen/test/multiprocess_test_case.py", line 199, in _run
    getattr(self, test_name)()
  File "/home/circleci/CrypTen/test/test_arithmetic.py", line 560, in test_conv2d_rectangular_image_many_channels
    self._conv2d((16, 7), 5)
  File "/home/circleci/CrypTen/test/test_arithmetic.py", line 622, in _conv2d
    self._check(encr_conv, reference, "%s failed" % func_name)
  File "/home/circleci/CrypTen/test/test_arithmetic.py", line 55, in _check
    self.assertTrue(test_passed, msg=msg)
  File "/usr/local/lib/python3.7/unittest/case.py", line 705, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : conv_transpose2d failed

** Process 1 ** :
Traceback (most recent call last):
  File "/home/circleci/CrypTen/test/multiprocess_test_case.py", line 199, in _run
    getattr(self, test_name)()
  File "/home/circleci/CrypTen/test/test_arithmetic.py", line 560, in test_conv2d_rectangular_image_many_channels
    self._conv2d((16, 7), 5)
  File "/home/circleci/CrypTen/test/test_arithmetic.py", line 622, in _conv2d
    self._check(encr_conv, reference, "%s failed" % func_name)
  File "/home/circleci/CrypTen/test/test_arithmetic.py", line 55, in _check
    self.assertTrue(test_passed, msg=msg)
  File "/usr/local/lib/python3.7/unittest/case.py", line 705, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : conv_transpose2d failed
```

2021-03-22 16:51 UTC, knottb requested changes

2021-03-22 16:51 UTC, knottb commented on crypten/cuda/cuda_tensor.py
> +        groups = kwargs["groups"] // nb2 if op in ["conv_transpose1d", "conv_transpose2d"] else 1
`conv_transpose2d` groups is giving incorrect result in unit test:

`test.test_arithmetic.TestArithmetic.test_conv2d_rectangular_image_many_channel`

2021-12-02 22:56 UTC, closed without merging